### ISSUE TITLE
Support for Google Chat

### ISSUE THREAD

**Issue by alexmt** [argoproj/notifications-engine#23]
By @aslafy-z: https://github.com/argoproj-labs/argocd-notifications/issues/243

It would be great to see notifications to [Google Chat](https://developers.google.com/hangouts/chat/how-tos/webhooks?hl=fr) directly integrated into Argo CD Notifications

**Comment by PhamQuang-512** [comment]
argocd notification to google chat get error "Failed to notify recipient {googlechat om-argocd} defined in resource argocd/testing-new-app: error creating client to webhook: no Google chat webhook configured for recipient om-argocd using the configuration in namespace argocd" resource=argocd/testing-new-app" although have done everything in this docs https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/googlechat/ (already config trigger)
