### ISSUE TITLE
Currently GitHubNotification have no other option than taking RepoURL from app.spec.source.repoURL

### ISSUE THREAD

**Issue by SebastianBakala-TomTom** [argoproj/notifications-engine#59]
The problem.
  My teammates are installing its apps by argo from helm-chart-repository and we're not able to use notification-plugin to push statusCheck to github repository which we specify. GitHub Service only takes it directly from application spec and there is no other option to override this value.

Could you please make it possible?

Thanks!

**Comment by ryota-sakamoto** [comment]
Would you provide more details?

**Comment by SebastianBakala-TomTom** [comment]
Hi @ryota-sakamoto.
Sure!

Notifications for github repositories are using `spec.source.repoURL` key from an application manifest [here](https://github.com/argoproj/notifications-engine/blob/master/pkg/services/github.go#L46).
I would be glad if I could to modify this behaviour eg. by using `metadata.annotations` (like in slack service).
This would really improve our cicd pipelines when so can install helm chart via argo and notify some custom github repository (eg. source-code repo).

Would it be possible to you?

**Comment by tback** [comment]
I can provide the/a use case for this issue:

I have separate repositories for the application (a node app) and operation (a repository containing a helm chart in my case). I use an ApplicationSet fed by the PullRequestGenerator to deploy preview environments. I want to inform users (other developers, qa, product) about the state of the preview environment through the status in the PR. Obviously, the PR is in the application repository that is monitored by the generator, not in the operations repository configured in the application template.

The github notifier however has a fix repoURL (https://github.com/argoproj/notifications-engine/blob/4d8552b0775f36fcecf3e394be2f8cf068ae0566/pkg/services/github.go#L46). 

A better name for this issue would be: Allow configuration of RepoURL and revision for GitHubNotification.
