### ISSUE TITLE
Structs/Lists/Maps should be automatically rendered as JSON to templates

### ISSUE THREAD

**Issue by WillSewell** [argoproj/notifications-engine#67]
# Summary

For webhook notification services, provide the ability to forward the entire Rollout as JSON.

# Use Cases

We would like to decide which fields to use within our service that handles notification webhooks, rather than within the notification template. This would allow us to reduce the coupling between the template and the webhook handling service that consumes the notifications (which currently have to agree on the schema). It would also cut down on the boilerplate that exists in our template definitions, which looks like:

```
{
  "deployment_name": "{{.rollout.spec.workloadRef.name}}",
  "current_step_index": "{{.rollout.status.currentStepIndex}}",
  "replicas": "{{.rollout.status.replicas}}"
  ...
}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Alternatively or preferably, we could add a built-in  `json` and `yaml` functions so that users could do this explicitly. e.g.:

```yaml
{{.rollout | json}}
```

**Comment by jessesuen** [comment]
I just saw in the code we use sprig, which contains a bunch of default functions
https://masterminds.github.io/sprig/defaults.html

So the following should be possible today:
```
{{.rollout | toJson}}
```

@WillSewell can you confirm?

**Comment by WillSewell** [comment]
That did the trick! Thank you. Would you like me to update the documentation to mention this?

**Comment by ju187** [comment]
Some times the rollout status condition has quotes, it may throw off unmarshalling
