### ISSUE TITLE
No Error When Grafana Notification Is Not Sent Successfully

### ISSUE THREAD

**Issue by joyce-ma** [argoproj/notifications-engine#77]
We were setting up our Grafana service but did not specify a `message` field in our notification template. The Grafana annotations were not being created as it was causing the following error in Grafana: 
`2022-02-09T20:21:11.649902048Zt=2022-02-09T20:21:11+0000 lvl=eror msg="Failed to save annotation" logger=context userId=0 orgId=1 uname= error="text field should not be empty" remote_addr=<IP address>`

### Expected
ArgoCD logs an error when Grafana returns a 400 error from its create annotation API.

### Actual
ArgoCD reported that the notification was sent successfully
```
"time="2022-02-09T20:21:11Z" level=info msg="Sending notification about condition 'on-deployed.[0].y7b5sbwa2Q329JYH755peeq-fBs' to '{grafana tenant-api}'" resource=score-argo/beehive-sandbox"
timestamp: "2022-02-09T20:21:11.614583720Z"
```
 https://github.com/argoproj/notifications-engine/blob/32519f8f68ec85d8ac3741d4ad52f7f5476ce5e7/pkg/controller/controller.go#L171

### Request
Adding a templates section to the documentation for Grafana notifications, similar to the docs for [Slack](https://argocd-notifications.readthedocs.io/en/stable/services/slack/#templates) or [email](https://argocd-notifications.readthedocs.io/en/stable/services/email/#template) notifications, could be helpful. It could explicitly state that notification template requires specifying the `message` field for Grafana annotations.

It could be helpful for [this method](https://github.com/argoproj/notifications-engine/blob/32519f8f68ec85d8ac3741d4ad52f7f5476ce5e7/pkg/services/grafana.go#L39) to check the status code of the Grafana response and return an error if the annotation was not created. It could also check whether `message` is an empty string and send an error message if it is.

**Comment by pasha-codefresh** [comment]
Great job, pr is merged. Thank you!
