### ISSUE TITLE
Support for GitHub deployments

### ISSUE THREAD

**Issue by ejhayes** [argoproj/notifications-engine#98]
It’d be great to add additional functionality to the GitHub integration so that it supports creating/updating deployments using the deployments API.

https://docs.github.com/en/rest/deployments/deployments

**Comment by hmajid2301** [comment]
I'd love this feature as well!

**Comment by jaredtbates** [comment]
I created a PR for creating deployments. I'm not sure how we could implement the update deployments part of this issue, because it would require preserving the deployment ID across multiple events. Any thoughts on that?
